apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - name: nginx
    image: nginx:1.19  
    env:
      - name: USERNAME  
        valueFrom:
          secretKeyRef:
            name: nginx-credentials
            key: username
      - name: PASSWORD
        valueFrom:  
          secretKeyRef:
            name: nginx-credentials
            key: password
