apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: nginx:1.19
            args:
            - /bin/sh
            - -c
            - nginx -g 'daemon off;'
          restartPolicy: OnFailure
