apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.19
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: nginx-secret
---  
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
stringData:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: nginx
  DB_PASSWORD: P@ssw0rd
