apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx 
    image: nginx:1.19
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: app-config  
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-logs
    emptyDir: {} 
  - name: nginx-cache
    emptyDir:
      medium: Memory    
  - name: app-config
    configMap:
      name: nginx-config
