apiVersion: v1
kind: Pod
metadata:
  name: nginx-multicontainer
spec:
  containers:
  - name: nginx
    image: nginx:1.19
    ports:
    - containerPort: 80
  - name: sidecar
    image: prom/prometheus
    args: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumeMounts:
    - name: prometheus-config  
      mountPath: /etc/prometheus
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']  
  volumes:
    - name: prometheus-config
      configMap:
       name: prometheus-config
