apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /tmp/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        log_format compression '$remote_addr - $remote_user [$time_local] '
                              '"$request" $status $upstream_addr '
                              '"$http_referer" "$http_user_agent"';

        server {
            listen 80;
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }
